version: '3.7'
services:
  hub:
    image: selenium/hub
    ports:
      - '9090:4444'

    environment:
      GRID_MAX_SESSION: 5
      GRID_BROWSER_TIMEOUT: 3000
      GRID_TIMEOUT: 3000
      
  chrome:
    image: selenium/node-chrome
    container_name: web-automation_chrome
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 4
      NODE_MAX_INSTANCES: 4
    volumes:
      - '/dev/shm:/dev/shm'
    ports:
      - '5555:5900'
    links:
      - hub
