version: '3.3'

services:

  hub:
    image: selenium/hub:latest
    volumes:
      - ./web/application:/application
    ports:
      - 4444:4444

  chrome:
    image: selenium/node-chrome:latest
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
